# Generated by Django 6.0 on 2026-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_blogcontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontributor',
            name='contribution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
