# Generated by Django 6.0 on 2026-01-11 15:07

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    BlogContributor = apps.get_model('blog', 'BlogContributor')

    for blog in Blog.objects.all():
        if blog.author:
            BlogContributor.objects.get_or_create(
                blog=blog,
                contributor=blog.author,
                defaults={
                    'contribution': 'Auteur principal'
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcontributor_contribution'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors),
    ]
