# Generated by Django 6.0 on 2025-12-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile_photo_alter_user_role'),
        ('blog', '0002_alter_blog_content_alter_photo_caption'),
    ]


    def create_groups(apps, schema_editor):
        User = apps.get_model('authentication', 'User')
        Group = apps.get_model('auth', 'Group')
        Permission = apps.get_model('auth', 'Permission')

        add_photo = Permission.objects.get(codename='add_photo')
        change_photo = Permission.objects.get(codename='change_photo')
        delete_photo = Permission.objects.get(codename='delete_photo')
        view_photo = Permission.objects.get(codename='view_photo')
        
        add_blog = Permission.objects.get(codename='add_blog')
        change_blog = Permission.objects.get(codename='change_blog')
        delete_blog = Permission.objects.get(codename='delete_blog')
        view_blog = Permission.objects.get(codename='view_blog')
        
        creator_permissions = [
            add_photo,
            change_photo,
            delete_photo,
            view_photo,
            add_blog,
            change_blog,
            delete_blog,
            view_blog,
            
        ]
        
        creators = Group(name='creators')
        creators.save()
        
        creators.permissions.set(creator_permissions)   

        subscribers = Group(name='subscribers')
        subscribers.save()
        subscribers.permissions.set([
            view_photo,
            view_blog,
        ])
        
        for user in User.objects.all():
            if user.role == 'CREATOR':
                creators.user_set.add(user)
            if user.role == 'SUBSCRIBER':
                subscribers.user_set.add(user)
                

    operations = [
        migrations.RunPython(create_groups)
    ]
